name: sms
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - attrs
  - numpy
  - jupyterlab
  - matplotlib
  - pytest
  - pyyaml
  - meshio
  - COMPAS
  - scipy
  - tqdm
  - h5py
  - cython
  - pyprog
