name: sms
channels:
  - conda-forge
  # - defaults
dependencies:
  - python=3.9
  - pip
  - pip:
    - attrs
    - numpy
    - ipython
    - ipykernel
    - matplotlib
    - pytest
    - meshio
    - scipy
    - h5py
    - pyprog
    - mpi4py
    - petsc4py
    - pyvista
    - trame
    - trame-vtk
    - trame-vuetify
    - seaborn
variables:
  PETSC_DIR: '/home/ingo/petsc'
  PETSC_ARCH: 'linux-gnu'
  SMS: '/home/ingo/Git/sms'
  PYTHONPATH: ':/home/ingo/Git/sms'


