name: sms-new
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - pip:
    - attrs
    - numpy
    - ipython
    - ipykernel
    - matplotlib
    - pytest
    - meshio
    - scipy
    - h5py
    - pyprog
    - mpi4py
    - petsc4py
    - pyvista
    - trame
    - trame-vtk
    - trame-vuetify
    - seaborn
    - jax
    - jaxlib
    - pyprecice
variables:
  PETSC_DIR: '/home/ingo/Git/petsc'
  PETSC_ARCH: 'linux-gnu'
  SMS: '/home/ingo/Git/sms'
  PYTHONPATH: ':/home/ingo/Git/sms'


