
project:
  type: website
bibliography: bibliography.bib

quartodoc:
  style: pkgdown
  dir: api
  package: library
  sections:
    - title: 
      desc: Test
      contents:
        - fvm.solver_jax.Settings


website:
  title: ""
  favicon: /images/favicon.svg
  search: 
    location: navbar
    type: overlay
  navbar:
    logo: /images/logo.png
    left:
      - text: "Software"
        href: software.qmd
      - text: "Playground"
        href: playground/playground.qmd
      - text: "Documentation"
        href: docs/index.qmd
      - text: "Tutorials"
        href: tutorials/index.qmd
      - text: "Publications"
        href: publications.qmd
      - text: "About"
        href: about.qmd
    right: 
      - icon: github
        menu:
          - text: Zoomy
            href: https://github.com/mbd-rwth/Zoomy
          - text: MBD
            href: https://github.com/mbd-rwth
      - text: "{{< iconify fa6-brands linkedin >}}"
        href: 'https://de.linkedin.com/company/rwth-mbd'

  sidebar:
    - id: tutorials 
      title: "Tutorials"
      style: "floating"
      contents:
        - tutorials/index.qmd
        - section: "Shallow Water"
          contents:
            - tutorials/swe/simple_numpy.ipynb
            - tutorials/swe/simple_jax.ipynb
        - section: "Poisson"
          contents:
            - tutorials/poisson/simple.ipynb
        - section: "VAM"
          contents:
            - tutorials/vam/simple.ipynb
        - section: "SME"
          contents:
            - tutorials/sme/simple.ipynb
            - tutorials/sme/minimal.ipynb
        - section: "AMReX"
          contents:
            - tutorials/amrex/from_DEM.ipynb
        - section: "Code Printers"
          contents:
            - tutorials/code_printers/to_amrex.ipynb
            - tutorials/code_printers/to_openfoam.ipynb
            - tutorials/code_printers/to_ufl.ipynb
        - section: "DolfinX"
          contents:
            - tutorials/dolfinx/dolfinx_demo.ipynb
    - id: documentation 
      title: "Documentation"
      style: "floating"
      contents:
        - section: "Getting-started"
          contents: 
            - docs/index.qmd
        - text: "Testing"
          href: ./pytest-report.html
        - text: "API"
          href: api/index.qmd

  page-footer:
    background: None
    foreground: None
    border: false
    left: "Copyright 2025, Ingo Steldermann"
    right: 
      - text: "Legal notice and data protection" 
        href: legal.qmd

  repo-url: https://github.com/mbd-rwth/Zoomy
  repo-actions: [edit, issue]
  repo-branch: main
  repo-subdir: web
  repo-link-target: "_blank"

format:
  html:
    theme: cosmo
    # embed-resources: true
    # self-contained-math: true
    css: custom.css
    toc: true
    html-math-method: mathjax
    include-in-header:
      - text: |
          <script>
          MathJax = {
            tex: {
              tags: 'ams'
            }
          };
          </script>
          <script data-goatcounter="https://ingosteldermann.goatcounter.com/count"
          async src="//gc.zgo.at/count.js"></script>



execute: 
  freeze: auto
  cache: true
